qibuild: auto-add missing projects
This fixes somewhat annoying qibuild behavior:

 $ cd worktree
 $ git clone git://newproj.git
 $ cd newproj
 $ qc
 ERROR:  no such project 'newproj'

Now instead of an error, qibuild will try its best
to fix the problem.

  $ qc
warning: Found a valid qiproject.xml but the
project name 'newproj' does not match any
buildable to project
Add the project to the worktree (Y/n)?

Change-Id: Ib8ade4f53ccaa318f1ed19c084f4c8b5385378b8