qisrc.worktree.checkout(): fix crash when there are no projects to checkout
Previously we were crashing with:
ValueError: max() arg is an empty sequence

Change-Id: Ib8d7c9f485f0e4ded9d3797e0cf354a6c51b31d3
Reviewed-on: http://gerrit.aldebaran.lan/62404
Tested-by: gerrit
Reviewed-by: vbarbaresi <vbarbaresi@aldebaran-robotics.com>
(cherry picked from commit 8b0c7b08d954100e24328f1e1c05ccf471214d12)